# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'native_ios_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for native_ios_app
  flutter_application_path = '../flutter_nps'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)


end


post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end